// Spirex Screensaver
// ---------------------
// Copyright (C) 2001, 2002, 2003 John Horigan
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// John Horigan can be contacted at john@glyphic.com or at
// John Horigan, 1209 Villa St., Mountain View, CA 94041-1123, USA
//
//
// portion of this file are
// (c) 1998 Lucian Wischik. You may do whatever you want with this code, without restriction.

#ifdef VC6
#define IDR_MANIFEST                    1
#endif

#define IDS_DESCRIPTION      1
#define ID_SPIREX_ICON  100
#define ID_UNINSTALL_ICON 101
#define DLG_CONFIG  102
#define IDC_THICK 103
#define IDC_LENGTH  104
#define IDT_LENGTH  105
#define IDC_COUNT 106
#define IDC_EVOLUTION 107
#define IDT_COUNT 108
#define IDC_RATE  110
#define IDT_RATE  111
#define IDT_EVOLUTION 112
#define IDT_PRESETS 113
#define IDC_PRESETS 114
#define ID_BOX1   115
#define ID_BOX2   116
#define IDC_PREVIEW 117
#define IDC_SAVE  118
#define IDC_DELETE  119
#define IDT_COPYRIGHT 122
#define IDC_URL 124
#define IDT_VERSION   130
#define IDC_TEXTURE_BROWSE    131
#define IDT_TEXTURE   132
#define IDC_COLOR   133
#define IDC_TEXTURE_CLEAR 134
#define IDT_TEXTURE2  135
#define IDC_PREVIEW_BUTTON  136
#define IDC_RANDOM  137
#define IDC_FIXED 138
#define IDC_TEXTURE   109
#define IDC_TEXTURE_UD 139
#define IDTM_RANDOM_PRESET 140
#define ID_BATTERY_BOX 141
#define IDT_RES_BATTERY 142
#define IDC_RES_BATTERY 143
#define IDC_BATTERY_NEVER 144
#define ID_BLANK_CURSOR 154
#define IDC_CHECK_UPDATES 155
#define DLG_UPDATE 156
#define IDT_UPDATE 157
#define IDC_NOT_NOW 158
#define IDC_STOP 159
#define IDC_GET_IT 160
#define IDC_SPIREX_ICON 161
#define IDTM_ANIMATE 162
#define IDC_POINTS 163
#define IDC_TRIAXIAL 164
#define IDC_MODE  165
#define ID_SETTINGSBOX 166
#define IDC_ADVANCED  167
#define DLG_ADVCONFIG 168
#define DLG_MAINCONFIG 169
#define IDC_GOHOME  170
#define IDC_RES_ALWAYS  171
#define IDC_RES_MULTI 172
#define IDT_RES_ALWAYS  196
#define IDT_RES_MULTI 197
#define IDC_DETAIL  173
#define ID_BORG 174
#define ID_EARTH  175
#define ID_EUROPA 176
#define ID_FLOWER 177
#define ID_MARS 178
#define ID_MOON 179
#define ID_ORIGAMI  180
#define ID_SPIREX 181
#define IDT_BORG "#174"
#define IDT_EARTH  "#175"
#define IDT_EUROPA "#176"
#define IDT_FLOWER "#177"
#define IDT_MARS "#178"
#define IDT_MOON "#179"
#define IDT_ORIGAMI  "#180"
#define IDT_SPIREX "#181"
#define ID_HOTCORNER_BOX 182
#define IDC_TL_CORNER 183
#define IDC_TR_CORNER 184
#define IDC_BL_CORNER 185
#define IDC_BR_CORNER 186
#define ID_TL_YES 187
#define ID_TR_YES 188
#define ID_BL_YES 189
#define ID_BR_YES 190
#define ID_TL_NO  191
#define ID_TR_NO  192
#define ID_BL_NO  193
#define ID_BR_NO  194
#define DLG_2D_CONFIG 195
#define IDT_HOT_CORNER 201
#define ID_PERF_BOX 202
#define IDT_DETAIL 198
#define IDT_COARSE 199
#define IDT_FINE 200

